
name: Generate schema (NPM 6)
on:
  - push

jobs:
  npm-install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.19.0
      uses: actions/setup-node@v1
      with:
        node-version: 12.19.0
    - run: npm --version
    - run: npm install
    - run: ./node_modules/.bin/apollo schema:download --endpoint=https://gitlab.com/api/graphql schema.json
